name: merge-check
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.2.0
          cache: 'npm'
      - name: Fetch necessary commits
        run: |
          commits=${{ github.event.pull_request.commits }}
          if [[ -n "$commits" ]]; then
            git fetch --depth="$(( commits + 1 ))"
          fi
      - name: Get SHA
        id: get-sha
        run: |
          echo "head_sha=$(git rev-parse "remotes/origin/${{ github.head_ref }}")" >> $GITHUB_OUTPUT
          echo "base_sha=$(git rev-parse "remotes/origin/${{ github.base_ref }}")" >> $GITHUB_OUTPUT
      - run: npm ci
      - name: Lint other than packages/
        run: |
          changed_files=$(git diff --name-only ${{ steps.get_sha.outputs.base_sha }} ${{ steps.get_sha.outputs.head_sha }})
          if [ $(echo "$changed_files" | grep -vc '^packages\/.*\/.*$') -gt 0 ]; then
            npm run eslint
          fi
      - name: Lint packages/
        run: |
          git diff --name-only ${{ steps.get-sha.outputs.base_sha }} ${{ steps.get-sha.outputs.head_sha }} |
          sed -nr 's/(^packages\/[^\/|.]*)\/.*$/\1/p' |
          sort -u |
          xargs -I WORKSPACE sh -c 'npm run eslint -w WORKSPACE || exit 1'
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.2.0
          cache: 'npm'
      - name: Fetch necessary commits
        run: |
          commits=${{ github.event.pull_request.commits }}
          if [[ -n "$commits" ]]; then
            git fetch --depth="$(( commits + 1 ))"
          fi
      - name: Get SHA
        id: get-sha
        run: |
          echo "head_sha=$(git rev-parse "remotes/origin/${{ github.head_ref }}")" >> $GITHUB_OUTPUT
          echo "base_sha=$(git rev-parse "remotes/origin/${{ github.base_ref }}")" >> $GITHUB_OUTPUT
      - run: npm ci
      - run: |
          exit 1
