name: merge-check
on:
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          commits=${{ github.event.pull_request.commits }}
          if [[ -n "$commits" ]]; then
            # Prepare enough depth for diffs with master
            git fetch --depth="$(( commits + 1 ))"
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - run: npm ci
      - run: |
          git diff --name-only $(git rev-parse "remotes/origin/${{github.base_ref}}") $(git rev-parse "remotes/origin/${{github.head_ref}}") |
          sed -nr 's/(^packages\/[^\/|.]*)\/.*$/\1/p' |
          sort -u |
          xargs -I WORKSPACE npm run test -w WORKSPACE
