name: merge-check
on:
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          commits=${{ github.event.pull_request.commits }}
          if [[ -n "$commits" ]]; then
            # Prepare enough depth for diffs with master
            git fetch --depth="$(( commits + 1 ))"
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: 'npm'
      # - run: npm ci
      - if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
        run: npm ci
      - run: npm ls --depth=0
      # - run: |
      #     git diff --name-only $(git rev-parse "remotes/origin/${{github.base_ref}}") $(git rev-parse "remotes/origin/${{github.head_ref}}") |
      #     sed -nr 's/(^packages\/[^\/|.]*)\/.*$/\1/p' |
      #     sort -u |
      #     xargs -I WORKSPACE npm run test -w WORKSPACE
