name: merge-check
on:
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - run: echo head_ref ${{ github.head_ref }}
      - run: echo base_ref ${{ github.base_ref }}
      - run: npm ci
      - run: |
          git diff --name-only $(git rev-parse main) $(git rev-parse HEAD) |
          sed -nr 's/(^packages\/[^\/|.]*)\/.*$/\1/p' |
          sort -u |
          xargs -I WORKSPACE npm run test -w WORKSPACE
