name: tag
on:
  workflow_dispatch:
    inputs:
      package:
        type: string
        description: 'Package name to be release'
        required: true
      is-dev:
        type: boolean
        description: 'Whether it is a developed version'
        required: true
jobs:
  generate-next-tag:
    runs-on: ubuntu-latest
    env:
      PACKAGE: ${{ github.event.inputs.package }}
      IS_DEV: ${{ github.event.inputs.is-dev }}
    outputs:
      tag: ${{ steps.generate-tag.outputs.tag }}
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate next tag
        id: generate-tag
        run: |
          if [ "$IS_DEV" = "true" ]; then
            new_tag=$(bash <(curl -Ss https://raw.githubusercontent.com/i5irin/sembump/v0.4.0/sembump.sh) -d -p "$PACKAGE/v" -w "packages/$PACKAGE")
          else
            new_tag=$(bash <(curl -Ss https://raw.githubusercontent.com/i5irin/sembump/v0.4.0/sembump.sh) -p "$PACKAGE/v" -w "packages/$PACKAGE")
          fi
          echo "tag=$new_tag" >> $GITHUB_OUTPUT
  tagging:
    runs-on: ubuntu-latest
    needs: generate-next-tag
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Put tag
        run: |
          git tag "${{ needs.generate-next-tag.outputs.tag }}"
          git push origin main --tags
