name: tag
on:
  workflow_dispatch:
    inputs:
      package:
        type: string
        description: 'Package name to be release'
        required: true
      is-dev:
        type: boolean
        description: 'Whether it is a developed version'
        required: true
jobs:
  determine-next:
    runs-on: ubuntu-latest
    env:
      PACKAGE: ${{ github.event.inputs.package }}
      IS_DEV: ${{ github.event.inputs.is-dev }}
    outputs:
      version: ${{ steps.get-next.outputs.version }}
      prev-sha: ${{ steps.get-prev.outputs.sha }}
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get next version
        id: get-next
        run: |
          git tag
          if [ "$IS_DEV" = "true" ]; then
            new_version=$(bash <(curl -Ss https://raw.githubusercontent.com/i5irin/sembump/v0.4.0/sembump.sh) -d -p "$PACKAGE/v" -w "packages/$PACKAGE")
          else
            new_version=$(bash <(curl -Ss https://raw.githubusercontent.com/i5irin/sembump/v0.4.0/sembump.sh) -p "$PACKAGE/v" -w "packages/$PACKAGE")
          fi
          echo "$new_version"
          echo "version=$new_version" >> $GITHUB_OUTPUT
  tag:
    runs-on: ubuntu-latest
    needs: determine-next
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Put tag
        run: |
          git tag "${{ needs.determine-next.outputs.version }}"
          git push origin main --tags
